version: "3.8"
services:
  postgres:
    container_name: pwc-web-postgres
    image: postgres:12.5
    # platform: linux/arm64/v8
    # platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      # postgres automatically initializes all sql files located in docker-entrypoint-initdb.d
      - ./postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres:
    driver: bridge
volumes:
  pgadmin:
  postgres:
