Tax:
  - name: Tax Preparation and Planning
Accounting and Reporting:
  - name: Bookkeeping, Preparation of Financial Statements and Compilations
  - name: QuickBooks Consulting and Training
  - name: Payroll Processing and Reporting
Assurance Audit:
  - name: Audits of Financial Statements
  - name: Reviews and Agreed-Upon Procedures
Risk Advisory:
  - name: Risk Assessment and Risk Management
  - name: Internal Audit
  - name: Regulatory and Compliance
Fraud Examinations:
  - name: Fraud Examinations and Investigations
Consulting:
  - name: CFO / Controller Services
  - name: Other
